### PR TITLE
Make Limit_cycle module compatible with the linear response module

### PR DESCRIPTION
**Pull request by oameye**
- [ ] Check on a toy model if gives the right results

### CODE REVIEW

**Comment by jkosata** [comment]
Is it ok if I pick this up or do you have some more local stuff to push? I was going to write a short doc page for the limit cycles to submit with our revised paper

**Comment by oameye** [comment]
@jkosata Yes ofcourse! Feel free to push this forward.

**Comment by jkosata** [comment]
Rebased to `master` and did some minor touches, more coming

**Comment by jkosata** [comment]
I've brushed up the `LimitCycles` module so that our new paper is reproducible, removed a small bug, added an example doc.

The output of `plot_linear_response` for limit cycles looks reasonable and we've used it successfully before, but I can't think of a simple test.

**Review by jkosata — APPROVED** [review]

**Pull request merged**
