### PR TITLE
replaced DataStructures.jl dependency with OrderedCollections.jl

### LINKED ISSUE #71: Change DataStructures.jl dependency with OrderedCollections.jl
### Discussed in https://github.com/NonlinearOscillations/HarmonicBalance.jl/discussions/70

<div type='discussions-op-text'>

<sup>Originally posted by **oameye** October 25, 2022</sup>
Hey hey, I noticed that we use DataStructures.jl, the parent of OrderedCollections.jl. However, I think, we only use the `OrderedDict` type defined in OrderedCollections.jl. Hence, we only need the  OrderedCollections.jl dependency. Although, opting for OrderedCollections.jl would not reduce are loading time by much. I think it is just cleaner to only load what you use. This is also suggested in the [SCIML style guide](https://docs.sciml.ai/SciMLStyle/dev/#Subpackaging-and-interface-packages-is-preferred-over-conditional-modules-via-Requires.jl).

image
</div>

### PR DESCRIPTION
**Pull request by oameye**
resolves #71

### CODE REVIEW

**Comment by jkosata** [comment]
Can you cap the version of OrderedCollections? Likely not crucial here but required by the General repo I think, see other caps in Project.toml

**Comment by oameye** [comment]
I see did not know that. Will remember for the future.

**Comment by oameye** [comment]
Why did it first did not error and now does?

**Comment by jkosata** [comment]
Looks like the load test failed, maybe try manually and diagnose?

**Comment by oameye** [comment]
Manually everything passes the tests
image

But the first commit also passes the tests and the second doens't, but nothing changes except the  capped the version of OrderedCollections.jl.

**Pull request closed without merging**
