### PR TITLE
Refactor classification to have additional keyword arguments

### PR DESCRIPTION
**Pull request by oameye**

### CODE REVIEW

**Comment by jkosata** [comment]
Why is this needed? The current paradigm is that whenever solutions are manipulated, a function is constructed which takes the variables in a fixed order. This function is constructed internally. You can also construct it yourself, but in this case why kwargs if these cannot change?

**Comment by oameye** [comment]
I need it for the classification of the parametrons. I classify the solutions through the normal transformation matrix which i need to give to the classification function.
With kwarg I do not have to change the classification function every time I change the topology of the network. 
I think it is a nice feature. But if you think it can affect performance?

**Comment by jkosata** [comment]
I checked and kwargs should have the same performance (not sure though).
Why not just define your function with the matrix you need and pass it to `classify_solutions!` ? Having a construct where a constant kwarg is fed into a function you yourself just defined in the background seems redundant.

**Comment by jkosata** [comment]
Ad performance: I checked a simple case but there have been issues with splatting (`...`) before (https://discourse.julialang.org/t/why-is-the-splat-operator-slow/77928) , I think this construct just opens more ways to mess up

**Comment by oameye** [comment]
Closed in favor of using anonymous functions, e.g., 
`classify_solutions!(result_ωλ, soln -> is_symmetric(soln; sym_basis=sym_basis), "symmetric")`

**Pull request closed without merging**
